### ISSUE TITLE
does WF on win7/32 need admin privs? - can't run it.

### ISSUE THREAD

**Issue by andrearicci** [google/WebFundamentals#1127]
I had a lot of iussues installing WF on windows as normal user on win7/32, shall I do it as admin? 
If so, can I then work as normal user?
here are some errors (running as user):
`D:\_WORK\WEB_SITES\webstarterkit>npm install`
`npm WARN engine imagemin@2.2.1: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"0.10.36","npm":"1.4.28"})`
 …
`npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0`
…
Error: Cannot find module 'readable-stream/transform'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\_WORK\WEB_SITES\webstarterkit\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\through2\through2.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm WARN optional dep failed, continuing imagemin-optipng@4.2.0
npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0

At the end of the process:
D:\_WORK\WEB_SITES\webstarterkit>gulp serve
[12:52:48] Local gulp not found in D:\_WORK\WEB_SITES\webstarterkit
[12:52:48] Try running: npm install gulp

So I do it, but then:
D:\_WORK\WEB_SITES\webstarterkit>gulp serve
[12:54:34] Using gulpfile D:\_WORK\WEB_SITES\webstarterkit\gulpfile.js
[12:54:34] Starting 'styles'...
[12:54:34] 'styles' errored after 20 ms
[12:54:34] Error: Cannot find module 'gulp-changed'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.defineProperty.get (D:\_WORK\WEB_SITES\webstarterkit\node_modules\gulp-load-plugins\index.js:48:18)
    at Gulp.gulp.task.$.useref.assets.searchPath (D:\_WORK\WEB_SITES\webstarterkit\gulpfile.js:90:13)
    at module.exports (D:\_WORK\WEB_SITES\webstarterkit\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\_WORK\WEB_SITES\webstarterkit\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\_WORK\WEB_SITES\webstarterkit\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\_WORK\WEB_SITES\webstarterkit\node_modules\gulp\node_modules\orchestrator\index.js:134:8)

I'm a designer, not a programmer, all these errors are too much for me. I thougth the system could be interesting but wish a fail-proof installation system.
Thank you

**Comment by PaulKinlan** [comment]
It is probably best to raise this in github.com/Google/Web-Starter-Kit
