### ISSUE TITLE
Local build is failing

### ISSUE THREAD

**Issue by Meggin** [google/WebFundamentals#1978]
Hey,

I checked my local build, and it was fine this morning. Did a pull and tried again, and now it's failing. Below I'm pasting in the error.

Note I tried updating gulp, jekyll and even updated kramdown, but still isn't working.

[10:40:48] Starting 'compile-jekyll:localhost'...
Configuration file: src/jekyll/_config/common.yml
Configuration file: src/jekyll/_config/appengine.yml
Configuration file: src/jekyll/_config/localhost.yml
            Source: src/jekyll
       Destination: build/langs
      Generating...
[10:40:52] 'compile-jekyll:localhost' errored after 3.32 s
[10:40:52] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/mkearney/WebFundamentals/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/mkearney/WebFundamentals/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/mkearney/WebFundamentals/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/mkearney/WebFundamentals/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
[10:40:52] 'develop' errored after 7.5 s
[10:40:52] Error in plugin 'run-sequence'
Message:
    An error occured in task 'compile-jekyll:localhost'.

**Comment by Meggin** [comment]
[failing.txt](https://github.com/google/WebFundamentals/files/6201/failing.txt)

**Comment by Meggin** [comment]
Pete fixed this, so closing.
