### ISSUE TITLE
Error: spawn dev_appserver.py ENOENT

### ISSUE THREAD

**Issue by redowy** [google/WebFundamentals#2598]
I got some error logs when I have tried to run the site,
My environment is Ubuntu 14.04:

root@user:/home/user/WebFundamentals/# gulp 
......
......
[05:20:04] Finished 'pretty-print-gae-info' after 1.66 ms
[05:20:04] Finished 'start-gae-dev-server' after 42 ms
[05:20:04] Starting 'dev-watch-tasks'...
[05:20:14] Finished 'dev-watch-tasks' after 9.87 s
[05:20:14] Finished 'develop' after 10 min
[05:20:14] Starting 'default'...
[05:20:14] Finished 'default' after 27 μs
events.js:142
      throw er; // Unhandled 'error' event
      ^
Error: spawn dev_appserver.py ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:179:32)
    at onErrorNT (internal/child_process.js:345:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)

**Comment by bmkmanoj** [comment]
I also seeing the same error, but on a Mac.

**Comment by wirandraw** [comment]
Hi, Actually logs were appeared because I have missed to following a step before **Running The Site**. I am hurrying to run **gulp** command after I have finished the 9th step of Installation Guide **npm install**. It mean I did not through. But generally, if we develop web app using npm we usually running **gulp** or **grunt serve** after **npm install** right?

I have missed to following:

10th Get the App Engine SDK and unzip into the google_appengine folder inside the project root. Add it to your path accordingly (in bash, $ PATH=./google_appengine:$PATH)

So, Probably It does't caused by WebFundamentals Platform. Now I can run the site on my localhost!
