### ISSUE TITLE
Unexpected attribute 'pagespeed' when gulping?

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#2974]
Can anyone reproduce this by upgrading to latest Google App Engine Python SDK for Mac (1.9.38 - 2016-05-25)?

```
$ gulp

---------------------------------

    Building all languages.
    Add --lang <Language Code> to build a specific language.

    Building all sections.
    Add --section <Section Folder Name> to build a specific section.

---------------------------------

[10:46:32] Using gulpfile ~/Repositories/kaycebasques/WebFundamentals/gulpfile.js
[10:46:32] Starting 'develop'...
[10:46:32] Starting 'clean'...
[10:46:32] Finished 'clean' after 228 ms
[10:46:32] Starting 'generate-dev-css'...
[10:46:32] Starting 'styles:clean'...
[10:46:32] Starting 'images:clean'...
[10:46:32] Starting 'fonts:clean'...
[10:46:32] Starting 'cp-scripts'...
[10:46:32] Starting 'scripts:clean'...
[10:46:32] Finished 'styles:clean' after 3.37 ms
[10:46:32] Starting 'compile-dev-css'...
[10:46:32] Finished 'fonts:clean' after 255 ms
[10:46:32] Starting 'cp-fonts'...
[10:46:32] Finished 'scripts:clean' after 285 ms
[10:46:32] Starting 'cp-third-party-style-scripts'...
[10:46:32] Starting 'transpile-scripts'...
[10:46:32] Finished 'transpile-scripts' after 1.14 ms
[10:46:32] Finished 'cp-fonts' after 53 ms
[10:46:32] Finished 'images:clean' after 401 ms
[10:46:32] Starting 'cp-images'...
[10:46:32] Starting 'cp-images:jekyll'...
[10:46:32] Starting 'cp-images:static'...
[10:46:36] compile-dev-css all files 2.57 MB
[10:46:36] Finished 'compile-dev-css' after 3.48 s
[10:46:36] Finished 'generate-dev-css' after 3.49 s
[10:46:36] Finished 'cp-images:jekyll' after 3.1 s
[10:46:36] Finished 'cp-third-party-style-scripts' after 3.23 s
[10:46:36] Finished 'cp-scripts' after 3.51 s
[10:46:36] Finished 'cp-images:static' after 3.15 s
[10:46:36] Finished 'cp-images' after 3.15 s
[10:46:36] Starting 'rm-jekyll-build-directory'...
[10:46:36] Finished 'rm-jekyll-build-directory' after 437 μs
[10:46:36] Starting 'compile-jekyll:localhost'...
Configuration file: src/jekyll/_config/common.yml
Configuration file: src/jekyll/_config/appengine.yml
Configuration file: src/jekyll/_config/localhost.yml
            Source: src/jekyll
       Destination: build/langs
      Generating... 
Skipping /showcase, moved to DevSite templates. 




                    done.
 Auto-regeneration: disabled. Use --watch to enable.
[10:48:17] Finished 'compile-jekyll:localhost' after 1.68 min
[10:48:17] Starting 'cp-showcase'...
[10:48:17] Finished 'cp-showcase' after 164 ms
[10:48:17] Starting 'gae:clean'...
[10:48:17] Finished 'gae:clean' after 1.57 ms
[10:48:17] Starting 'copy-appengine-config'...
[10:48:17] Finished 'copy-appengine-config' after 5.11 ms
[10:48:17] Starting 'start-gae-dev-server'...
[10:48:17] Starting 'spawn-gae-dev-command'...
[10:48:17] Finished 'spawn-gae-dev-command' after 5.26 ms
[10:48:17] Starting 'pretty-print-gae-info'...

---------------------------------

    Server is on: http://localhost:7331
    BrowserSync is on: http://localhost:7332

---------------------------------

[10:48:17] Finished 'pretty-print-gae-info' after 161 μs
[10:48:17] Finished 'start-gae-dev-server' after 6.62 ms
[10:48:17] Starting 'dev-watch-tasks'...
[10:48:19] Finished 'dev-watch-tasks' after 1.74 s
[10:48:19] Finished 'develop' after 1.77 min
[10:48:19] Starting 'default'...
[10:48:19] Finished 'default' after 4.07 μs
[10:48:19] Traceback (most recent call last):
  File "/usr/local/bin/dev_appserver.py", line 84, in <module>
    _run_file(__file__, globals())
  File "/usr/local/bin/dev_appserver.py", line 80, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1040, in <module>
    main()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1033, in main
    dev_server.start(options)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 758, in start
    options.config_paths, options.app_id)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 831, in __init__
    module_configuration = ModuleConfiguration(config_path, app_id)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 127, in __init__
    self._config_path)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 424, in _parse_configuration
    config, files = appinfo_includes.ParseAndReturnIncludePaths(f)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/appinfo_includes.py", line 82, in ParseAndReturnIncludePaths
    appyaml = appinfo.LoadSingleAppInfo(appinfo_file)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/appinfo.py", line 2192, in LoadSingleAppInfo
    listener.Parse(app_info)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/yaml_listener.py", line 227, in Parse
    self._HandleEvents(self._GenerateEventParameters(stream, loader_class))
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/yaml_listener.py", line 178, in _HandleEvents
    raise yaml_errors.EventError(e, event_object)
google.appengine.api.yaml_errors.EventError: Unexpected attribute 'pagespeed' for object of type AppInfoExternal.
  in "build/app.yaml", line 6, column 3

/Users/kayce/Repositories/kaycebasques/WebFundamentals/gulp-tasks/gae.js:63
      throw new Error('An error occured with App Engine, please look ' +
      ^

Error: An error occured with App Engine, please look through the logs to find the problem.
    at ChildProcess.<anonymous> (/Users/kayce/Repositories/kaycebasques/WebFundamentals/gulp-tasks/gae.js:63:13)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)
```

Commenting out the `pagespeed` attribute in `appengine-config/app.yaml` resolves the error...

I've been wrangling with a bunch of weird errors across unrelated projects on my laptop today, so this may just be an environment issue.

**Comment by PaulKinlan** [comment]
You need to remove the pagespeed section from the app.yaml iirc.  It has been removed from App Engine.
