### ISSUE TITLE
Ubuntu issue with `pip install markdown -t ./gae/lib`

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#3498]
```
paulkinlan@gipid:~/WebFundamentals$ pip install markdown -t ./gae/lib
Collecting markdown
  Downloading Markdown-2.6.7.zip (413kB)
    100% |████████████████████████████████| 419kB 2.0MB/s 
Building wheels for collected packages: markdown
  Running setup.py bdist_wheel for markdown ... done
  Stored in directory: /home/paulkinlan/.cache/pip/wheels/34/53/13/36d28723fa9a091576fbb516003d33085a114f35b823faf05e
Successfully built markdown
Installing collected packages: markdown
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/share/python-wheels/setuptools-20.10.1-py2.py3-none-any.whl/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 289, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```

**Comment by petele** [comment]
@PaulKinlan reported that even though it failed on install, things still seem to work; and that StackOverflow recommends using `easy_install` instead.

**Comment by petele** [comment]
I think this is fixed since moving to master.
