### ISSUE TITLE
gcloud 157 application name workaround

### ISSUE THREAD

**Issue by lucab85** [google/WebFundamentals#4659]
Updated my workstation to gcloud sdk 157 and then failed to start the appserver on my localhost:

     npm start

FULL LOG:
      > WebFundamentals@2.0.0 start /home/luke/prj/github/WebFundamentals
      > ./start-appengine.sh

     Starting server on: http://localhost:8080/
     Traceback (most recent call last):
       File "/usr/lib/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 103, in      <module>
         _run_file(__file__, globals())
       File "/usr/lib/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 97, in _run_file
         execfile(_PATHS.script_file(script_name), globals_)
       File "/usr/lib/google-cloud-     sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 322, in           <module>
              main()
            File "/usr/lib/google-cloud-     sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 310, in      main
         dev_server.start(options)
       File "/usr/lib/google-cloud-     sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 106, in      start
         env_variables=parsed_env_variables)
       File "/usr/lib/google-cloud-     sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py",      line 851, in __init__
         env_variables)
       File "/usr/lib/google-cloud-     sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py",      line 131, in __init__
         self._config_path)
       File "/usr/lib/google-cloud-     sdk/platform/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 443, in _parse_configuration
         config.application = self._forced_app_id
       File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/validation.py",      line 361, in __setattr__
         value = self.GetValidator(key)(value, key)
       File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/validation.py",      line 599, in __call__
         return self.Validate(value, key)
       File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/validation.py",      line 881, in Validate
         return self.validator(value, key)
       File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/validation.py",      line 599, in __call__
         return self.Validate(value, key)
       File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/validation.py",      line 955, in Validate
         '\'%s\'' % (value, key, self.re.pattern))
     google.appengine.api.validation.ValidationError: Value 'None' for application does not match      expression '^(?:(?:[a-z\d\-]{1,100}\~)?(?:(?!\-)[a-z\d\-\.]{1,100}:)?(?!-)[a-z\d\-]{0,99}[a-z\d])$'
     
     npm ERR! Linux 4.4.0-78-generic
     npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
     npm ERR! node v4.2.6
     npm ERR! npm  v3.5.2
     npm ERR! code ELIFECYCLE
     npm ERR! WebFundamentals@2.0.0 start: `./start-appengine.sh`
     npm ERR! Exit status 1
     npm ERR! 
     npm ERR! Failed at the WebFundamentals@2.0.0 start script './start-appengine.sh'.
     npm ERR! Make sure you have the latest version of node.js and npm installed.
     npm ERR! If you do, this is most likely a problem with the WebFundamentals package,
     npm ERR! not with npm itself.
     npm ERR! Tell the author that this fails on your system:
     npm ERR!     ./start-appengine.sh
     npm ERR! You can get information on how to open an issue for this project with:
     npm ERR!     npm bugs WebFundamentals
     npm ERR! Or if that isn't available, you can get their info via:
     npm ERR!     npm owner ls WebFundamentals
     npm ERR! There is likely additional logging output above.
     
     npm ERR! Please include the following file with any support request:
     npm ERR!     /home/luke/prj/github/WebFundamentals/npm-debug.log
     
 
My workaround is to add application name by hand to bypass the "None" value (ref. https://stackoverflow.com/questions/44363876/dev-appserver-fails-to-launch-on-ubuntu-docker-container-validationerror-value):

     dev_appserver.py app.yaml -A webfundamentals --dev_appserver_log_level warning --port 8080

I hope there is a better solution but I can't find it! "application" in "app.yaml" won't work.

**Comment by lucab85** [comment]
Fixed with gcloud 161.
