### ISSUE TITLE
Local server can't display ToC

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#5723]
When I run `start-appengine.sh` and then view `http://localhost:8080/web/tools/lighthouse/audits/password-pasting` I get the following error:

```
INFO     2018-01-30 18:30:40,350 appengine_main.py:122] 200 /web/tools/lighthouse/audits/password-pasting
INFO     2018-01-30 18:39:30,707 appengine_main.py:86] GET /web/tools/lighthouse/audits/password-pasting?hl=en
ERROR    2018-01-30 18:39:30,800 devsiteHelper.py:107]  - ReadFile failed trying to find: tools/puppeteer/_src/api_section.yaml
ERROR    2018-01-30 18:39:30,801 devsiteHelper.py:159] Error in parseBookYaml
Traceback (most recent call last):
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 156, in parseBookYaml
    upperTabs.append(expandBook(upperTab))
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 176, in expandBook
    result[k] = expandBook(v, lang)
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 176, in expandBook
    result[k] = expandBook(v, lang)
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 185, in expandBook
    results.append(expandBook(item, lang))
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 176, in expandBook
    result[k] = expandBook(v, lang)
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 183, in expandBook
    results = results + expandBook(newItems['toc'], lang)
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 185, in expandBook
    results.append(expandBook(item, lang))
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 176, in expandBook
    result[k] = expandBook(v, lang)
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 185, in expandBook
    results.append(expandBook(item, lang))
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 176, in expandBook
    result[k] = expandBook(v, lang)
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 182, in expandBook
    newItems = yaml.load(readFile(item['include'], lang))
  File "/Users/kayce/SDKs/google-cloud-sdk/platform/google_appengine/lib/yaml-3.10/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/Users/kayce/SDKs/google-cloud-sdk/platform/google_appengine/lib/yaml-3.10/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/Users/kayce/SDKs/google-cloud-sdk/platform/google_appengine/lib/yaml-3.10/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/Users/kayce/SDKs/google-cloud-sdk/platform/google_appengine/lib/yaml-3.10/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/Users/kayce/SDKs/google-cloud-sdk/platform/google_appengine/lib/yaml-3.10/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
AttributeError: 'NoneType' object has no attribute 'read'
ERROR    2018-01-30 18:39:30,810 devsiteHelper.py:273]  - Unable to read or parse primary book.yaml
Traceback (most recent call last):
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 236, in getLeftNav
    for upperTab in bookYaml['upper_tabs']:
TypeError: 'NoneType' object has no attribute '__getitem__'
ERROR    2018-01-30 18:39:30,810 devsiteHelper.py:274] 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 236, in getLeftNav
    for upperTab in bookYaml['upper_tabs']:
TypeError: 'NoneType' object has no attribute '__getitem__'
ERROR    2018-01-30 18:39:30,810 devsiteHelper.py:212] Unable to read/parse the lower tabs
Traceback (most recent call last):
  File "/Users/kayce/Repositories/google/WebFundamentals/devsiteHelper.py", line 201, in getLowerTabs
    for tab in bookYaml['upper_tabs']:
TypeError: 'NoneType' object has no attribute '__getitem__'
INFO     2018-01-30 18:39:30,827 appengine_main.py:122] 200 /web/tools/lighthouse/audits/password-pasting
```

Still seeing this after error after running `npm run clean && npm run build`

**Comment by petele** [comment]
CC: @ebidel - this is happening because the TOC file for puppeteer isn't on your machine, and the TOC generation was dying. I've made it fail more gracefully, but, it introduces a side effect that when the TOC is missing, it's not immediately obvious.
