### ISSUE TITLE
Error viewing staged and local site

### ISSUE THREAD

**Issue by philipwalton** [google/WebFundamentals#6636]
You can see the issue on the staging server here:

https://pr-6635-dot-web-central.appspot.com/web/tools/

<img width="674" alt="screen shot 2018-09-18 at 11 27 26 am" src="https://user-images.githubusercontent.com/326742/45708299-dec65200-bb35-11e8-8999-c305a62669f4.png">

And here's the error reported from the local stack trace:

```
ERROR    2018-09-18 18:17:16,509 appengine_main.py:130] 500 /web/updates/
Traceback (most recent call last):
  File "/Users/philipwalton/Projects/google/WebFundamentals/appengine_main.py", line 104, in get
    response = devsiteIndex.getPage(path, lang)
  File "/Users/philipwalton/Projects/google/WebFundamentals/devsiteIndex.py", line 24, in getPage
    return devsiteParseYAML.parse(requestPath, fileLocation, content, lang)
  File "/Users/philipwalton/Projects/google/WebFundamentals/devsiteParseYAML.py", line 22, in parse
    if page['body_class']:
KeyError: 'body_class'
```

**Comment by petele** [comment]
Fixed in 10fe81432b8b934f79160d417197d0f3f2acd64d

You can either cherry pick that commit into your PR, or change line 22 of `devsiteParseYAML.py` to:
```
if 'body_class' in page:
```
